dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

env:
  - VERSION=5.0.7
  - VERSION=5.0.7 VARIANT=php7
  - VERSION=6.0.5
  - VERSION=6.0.5 VARIANT=php7
  - VERSION=7.0.0
  - VERSION=7.0.0 VARIANT=php7

script:
  - v="${VERSION}${VARIANT:+-$VARIANT}"
  - cd "images/$v"
  - docker build -t "madmath03/docker-dolibarr:$v" .
  - docker images

notifications:
  email: false
