dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - image="monogramm/docker-dolibarr:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "images/${VERSION}/${VARIANT}"

after_script:
  - docker images
  - docker run -d "$image" "images/${VERSION}/${VARIANT}"

notifications:
  email: false

env: # Environments
    - VERSION=7.0 VARIANT=fpm
    - VERSION=7.0 VARIANT=apache
    - VERSION=6.0 VARIANT=fpm
    - VERSION=6.0 VARIANT=apache
    - VERSION=5.0 VARIANT=fpm
    - VERSION=5.0 VARIANT=apache
